### PR TITLE
New app build errors

### PR DESCRIPTION
**Pull request by snigdhaAgarwal**
- importlib version was creating build issues
- check_bbox returns a tuple which can be handled by the LHS. The [0] was not required.
- Also suggest adding "conda upgrade --all -y" in the README to avoid some package corruption errors.

### CODE REVIEW

**Comment by pranathivemuri** [comment]
did this fix releasing your app?

**Review by pranathivemuri — APPROVED** [review]

**Comment by snigdhaAgarwal** [comment]
> did this fix releasing your app?

Yes!

**Comment by pranathivemuri** [comment]
so, what was the error?

**Comment by pranathivemuri** [comment]
If you do not have any additional commits to push, please merge the PR. next time - make sure to assign me as a reviewer as well as assignees - if you don't github won't notify me that you have opened a Pull Request. I only checked this PR because of your update slackbot notification

**Comment by snigdhaAgarwal** [comment]
> so, what was the error or error traceback with the initial app?

Conda upgrade fixed this error 
- AttributeError: module ‘natsort’ has no attribute ‘compat’
and allowed the app to run successfully.

**Pull request merged**
